### ISSUE TITLE
I meet an issue when use my custom data for 2 classes

### ISSUE THREAD

**Issue by sinnuswong** [getalp/Lightweight-Transformer-Models-For-HAR-on-Mobile-Devices#6]
I meet an issue when use my custom data for 2 classes,
the logs is below:

Data shape: (2173, 25, 6)
Labels shape: (2173, 2)
segment Time 
[0, 16]
Num GPUs Available:  1
(1043, 25, 6)
(1043, 2)
(1130, 2)
[[1 0]
 [1 0]
 [1 0]
 ...
 [0 1]
 [0 1]
 [0 1]]
Data shape: (2173, 25, 6)
Labels shape: (2173, 2)
(1901, 2)
(272, 25, 6)
(272, 2)
Traceback (most recent call last):
  File "F:\Lightweight-Transformer-Models-For-HAR-on-Mobile-Devices\mytrain.py", line 238, in <module>
    model_classifier = model.mobileHART_XS(input_shape, activityCount)
  File "F:\Lightweight-Transformer-Models-For-HAR-on-Mobile-Devices\model.py", line 603, in mobileHART_XS
    gyroX = conv_block(inputs[:,:,3:],filters=filterCount[0])
  File "F:\Lightweight-Transformer-Models-For-HAR-on-Mobile-Devices\model.py", line 428, in conv_block
    return conv_layer(x)
  File "F:\Lightweight-Transformer-Models-For-HAR-on-Mobile-Devices\venv\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "F:\Lightweight-Transformer-Models-For-HAR-on-Mobile-Devices\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 1969, in _create_c_op
    raise ValueError(e.message)
ValueError: Exception encountered when calling layer "conv1d_1" (type Conv1D).

Depth of filter must not be 0 for '{{node conv1d_1/Conv1D}} = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], explicit_paddings=[], padding="SAME", strides=[1, 1, 2, 1], use_cudnn_on_gpu=true](conv1d_1/Conv1D/Exp
andDims, conv1d_1/Conv1D/ExpandDims_1)' with input shapes: [?,1,25,0], [1,3,0,8].

Call arguments received by layer "conv1d_1" (type Conv1D):
  • inputs=tf.Tensor(shape=(None, 25, 0), dtype=float32)

can you give some help?

**Comment by Sannaraek** [comment]
Hello,

Its more likely that the problem is due to a change in input shape. 
In our experiment we use an input shape of (None,128,6), while as your input shape is (None, 25, 6)

The kernel size and depth of the conv layer was specifically chosen for our input dimension. 
In your case, you must again choose the corresponding hyper-parameters most suited for your input dimension.

Using the same hyper-parameter we provided led to passing a 0 for one of the inputs (None, 25, 0) which causes the error (base on  the logs you gave me)

Hope this helps!

**Comment by sinnuswong** [comment]
@Sannaraek thanks for help, fixed this issue.
Models really stunning
