### ISSUE TITLE
Conv2DCustomBackpropFilterOp only supports NHWC.

### ISSUE THREAD

**Issue by ryzn0518** [getalp/Lightweight-Transformer-Models-For-HAR-on-Mobile-Devices#9]
when run as the python=3.7.0, pip install -r requirement.txt

I run this code in google colab. it also errors again.
```
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
/tmp/ipykernel_308479/3557957218.py in <module>
     17     verbose=showTrainVerbose,
     18     class_weight=class_weights,
---> 19     callbacks=[checkpoint_callback],
     20 )
     21 end_time = time.time() - start_time

~/anaconda3/envs/3.7/lib/python3.7/site-packages/keras/utils/traceback_utils.py in error_handler(*args, **kwargs)
     68             # To get the full stack trace, call:
     69             # `tf.debugging.disable_traceback_filtering()`
---> 70             raise e.with_traceback(filtered_tb) from None
     71         finally:
     72             del filtered_tb

~/anaconda3/envs/3.7/lib/python3.7/site-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     53     ctx.ensure_initialized()
     54     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 55                                         inputs, attrs, num_outputs)
     56   except core._NotOkStatusException as e:
     57     if name is not None:

InvalidArgumentError: Graph execution error:

Detected at node 'gradient_tape/model/liteFormer_1/conv1d/Conv2DBackpropFilter' defined at (most recent call last):
    File "/home/user/anaconda3/envs/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/home/user/anaconda3/envs/3.7/lib/python3.7/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/home/user/anaconda3/envs/3.7/lib/python3.7/site-packages/ipykernel_launcher.py", line 17, in <module>
      app.launch_new_instance()
    File "/home/user/anaconda3/envs/3.7/lib/python3.7/site-packages/traitlets/config/application.py", line 1043, in launch_instance
      app.start()
    File "/home/user/anaconda3/envs/3.7/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 712, in start
      self.io_loop.start()
    File "/home/user/anaconda3/envs/3.7/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 215, in start
      self.asyncio_loop.run_forever()
    File "/home/user/anaconda3/envs/3.7/lib/python3.7/asyncio/base_events.py", line 523, in run_forever
      self._run_once()
    File "/home/user/anaconda3/envs/3.7/lib/python3.7/asyncio/base_events.py", line 1758, in _run_once
      handle._run()
    File "/home/user/anaconda3/envs/3.7/lib/python3.7/asyncio/events.py", line 88, in _run
      self._context.run(self._callback, *self._args)
    File "/home/user/anaconda3/envs/3.7/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
      await self.process_one()
    File "/home/user/anaconda3/envs/3.7/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 499, in process_one
      await dispatch(*args)
    File "/home/user/anaconda3/envs/3.7/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
      await result
    File "/home/user/anaconda3/envs/3.7/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 730, in execute_request
      reply_content = await reply_content
    File "/home/user/anaconda3/envs/3.7/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 387, in do_execute
      cell_id=cell_id,
    File "/home/user/anaconda3/envs/3.7/lib/python3.7/site-packages/ipykernel/zmqshell.py", line 528, in run_cell
      return super().run_cell(*args, **kwargs)
    File "/home/user/anaconda3/envs/3.7/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2976, in run_cell
      raw_cell, store_history, silent, shell_futures, cell_id
    File "/home/user/anaconda3/envs/3.7/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3030, in _run_cell
      return runner(coro)
    File "/home/user/anaconda3/envs/3.7/lib/python3.7/site-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
      coro.send(None)
    File "/home/user/anaconda3/envs/3.7/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3258, in run_cell_async
      interactivity=interactivity, compiler=compiler, result=result)
    File "/home/user/anaconda3/envs/3.7/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
      if (await self.run_code(code, result,  async_=asy)):
    File "/home/user/anaconda3/envs/3.7/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3553, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "/tmp/ipykernel_308479/3557957218.py", line 19, in <module>
      callbacks=[checkpoint_callback],
    File "/home/user/anaconda3/envs/3.7/lib/python3.7/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/home/user/anaconda3/envs/3.7/lib/python3.7/site-packages/keras/engine/training.py", line 1564, in fit
      tmp_logs = self.train_function(iterator)
    File "/home/user/anaconda3/envs/3.7/lib/python3.7/site-packages/keras/engine/training.py", line 1160, in train_function
      return step_function(self, iterator)
    File "/home/user/anaconda3/envs/3.7/lib/python3.7/site-packages/keras/engine/training.py", line 1146, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/user/anaconda3/envs/3.7/lib/python3.7/site-packages/keras/engine/training.py", line 1135, in run_step
      outputs = model.train_step(data)
    File "/home/user/anaconda3/envs/3.7/lib/python3.7/site-packages/keras/engine/training.py", line 997, in train_step
      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "/home/user/anaconda3/envs/3.7/lib/python3.7/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 577, in minimize
      loss, var_list=var_list, grad_loss=grad_loss, tape=tape
    File "/home/user/anaconda3/envs/3.7/lib/python3.7/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 635, in _compute_gradients
      tape, loss, var_list, grad_loss
    File "/home/user/anaconda3/envs/3.7/lib/python3.7/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 510, in _get_gradients
      grads = tape.gradient(loss, var_list, grad_loss)
Node: 'gradient_tape/model/liteFormer_1/conv1d/Conv2DBackpropFilter'
Conv2DCustomBackpropFilterOp only supports NHWC.
	 [[{{node gradient_tape/model/liteFormer_1/conv1d/Conv2DBackpropFilter}}]] [Op:__inference_train_function_34891]
```

**Comment by Sannaraek** [comment]
Hello,

This was a Tensorflow issue where the model could only be trained on GPU, as was also previously reported (https://github.com/getalp/Lightweight-Transformer-Models-For-HAR-on-Mobile-Devices/issues/5)

I had some time and went ahead to update the script :) 

Please pull the latest update

The code/pipeline now works with CPU and Tensorflow 2.18.*, (tested on my machine)

Good luck!
